// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgqaJfdYwr3NpXBD_PWWdQ9jIuY2SlcVg',
    appId: '1:709427293394:web:46046567b08cd17e76d10b',
    messagingSenderId: '709427293394',
    projectId: 'carry-or-drag',
    authDomain: 'carry-or-drag.firebaseapp.com',
    storageBucket: 'carry-or-drag.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC9iFy3XQSh4Rn9l4WbXCsgk_nBTBhq9E',
    appId: '1:709427293394:android:5da17adb468faf5076d10b',
    messagingSenderId: '709427293394',
    projectId: 'carry-or-drag',
    storageBucket: 'carry-or-drag.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRUzJ-109_o2e9xr3GZFhuraZPC2favzY',
    appId: '1:709427293394:ios:6d4bfb4cfdc4d1fd76d10b',
    messagingSenderId: '709427293394',
    projectId: 'carry-or-drag',
    storageBucket: 'carry-or-drag.appspot.com',
    iosBundleId: 'com.example.carryOrDrag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRUzJ-109_o2e9xr3GZFhuraZPC2favzY',
    appId: '1:709427293394:ios:6d4bfb4cfdc4d1fd76d10b',
    messagingSenderId: '709427293394',
    projectId: 'carry-or-drag',
    storageBucket: 'carry-or-drag.appspot.com',
    iosBundleId: 'com.example.carryOrDrag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgqaJfdYwr3NpXBD_PWWdQ9jIuY2SlcVg',
    appId: '1:709427293394:web:f34d22641da8aeb676d10b',
    messagingSenderId: '709427293394',
    projectId: 'carry-or-drag',
    authDomain: 'carry-or-drag.firebaseapp.com',
    storageBucket: 'carry-or-drag.appspot.com',
  );
}
